# Path B GT - treino e avaliação em sequência (B1, B3, B4)

Este notebook reutiliza o mesmo pré-processamento do Path B e roda, em sequência, o treino e a avaliação dos classificadores B1, B3 e B4 usando crops GT, com células separadas por path.

Passos cobertos:
- Selecionar detector YOLO;
- Pré-processamento dedicado do Path B (idempotente);
- Treinos em GT crops (B1, B3, B4) em células separadas;
- Avaliações combinadas com e sem TTA+WBF em células separadas;
- Ranqueamento final entre B1, B3 e B4.

In [1]:
from pathlib import Path
import os
import sys
import shlex
import subprocess
import shutil
import torch
import pandas as pd
import json

WORKSPACE = Path('/workspace')
REPO_ROOT = WORKSPACE / 'TrashScan'

DATA_DIR = REPO_ROOT / 'data'
TRAIN_DIR = REPO_ROOT / 'train' / 'paths'
EVAL_DIR = REPO_ROOT / 'eval'

EXTERNAL_DIR = WORKSPACE / 'external_datasets'
TACO_DIR = WORKSPACE / 'TACO'
PROCESSED_DIR = WORKSPACE / 'processed_5cls'

DATASET_YAML_PATH_B = PROCESSED_DIR / 'dataset_path_B.yaml'

RUNS_PATH_A_DIR = WORKSPACE / 'runs' / 'path_A'
MLFLOW_DIR = Path('/root/mlflow')
RESULTS_PATH_B_DIR = WORKSPACE / 'results_path_B'

TRAIN_PATH_B_SCRIPT = TRAIN_DIR / 'train_path_B.py'
EVAL_PATH_B_COMBINED_SCRIPT = EVAL_DIR / 'evaluate_path_B_combined.py'

for p in [MLFLOW_DIR, RESULTS_PATH_B_DIR]:
    p.mkdir(parents=True, exist_ok=True)

print('Python             =', sys.executable)
print('REPO_ROOT          =', REPO_ROOT)
print('PROCESSED_DIR      =', PROCESSED_DIR)
print('DATASET_YAML_PATH_B=', DATASET_YAML_PATH_B)
print('RUNS_PATH_A_DIR    =', RUNS_PATH_A_DIR)
print('RESULTS_PATH_B_DIR =', RESULTS_PATH_B_DIR)
print('TRAIN_PATH_B_SCRIPT=', TRAIN_PATH_B_SCRIPT)
print('EVAL_SCRIPT        =', EVAL_PATH_B_COMBINED_SCRIPT)


def run_cmd(cmd, cwd=WORKSPACE, env=None):
    print('$', ' '.join(shlex.quote(str(x)) for x in cmd))
    return subprocess.run([str(x) for x in cmd], cwd=str(cwd), env=env, check=True)

Python             = /workspace/.venv/bin/python
REPO_ROOT          = /workspace/TrashScan
PROCESSED_DIR      = /workspace/processed_5cls
DATASET_YAML_PATH_B= /workspace/processed_5cls/dataset_path_B.yaml
RUNS_PATH_A_DIR    = /workspace/runs/path_A
RESULTS_PATH_B_DIR = /workspace/results_path_B
TRAIN_PATH_B_SCRIPT= /workspace/TrashScan/train/paths/train_path_B.py
EVAL_SCRIPT        = /workspace/TrashScan/eval/evaluate_path_B_combined.py

In [2]:
if torch.cuda.is_available():
    DEVICE = '0'
    gpu_name = torch.cuda.get_device_properties(0).name
else:
    DEVICE = 'cpu'
    gpu_name = 'cpu'

print('Device:', DEVICE)
print('GPU:', gpu_name)

EPOCHS = 300
BATCH = 8
LR = 5e-5
PATIENCE = 15

EVAL_IMGSZ = 640
EVAL_DET_CONF = 0.001
EVAL_DET_IOU = 0.6

TTA_SCALES = ['512', '640', '768']
TTA_WBF_IOU = '0.55'
TTA_SKIP_BOX_THR = '0.001'

CONFIGS = [
    {
        'key': 'b1',
        'label': 'B1 (resnet50)',
        'classifier': 'resnet50',
        'run_dir': WORKSPACE / 'runs' / 'path_B_gt_b1',
    },
    {
        'key': 'b3',
        'label': 'B3 (vit_b16_imagenet)',
        'classifier': 'vit_b16_imagenet',
        'run_dir': WORKSPACE / 'runs' / 'path_B_gt_b3',
    },
    {
        'key': 'b4',
        'label': 'B4 (vit_l16_imagenet)',
        'classifier': 'vit_l16_imagenet',
        'run_dir': WORKSPACE / 'runs' / 'path_B_gt_b4',
    },
]

B1, B3, B4 = CONFIGS

for cfg in CONFIGS:
    cfg['run_dir'].mkdir(parents=True, exist_ok=True)

Device: 0
GPU: NVIDIA RTX 4000 Ada Generation

## 1) Selecionar detector YOLO

O treino em GT crops não usa o detector para gerar os exemplos. Ainda assim, o script pede `--detector_weights`, e a avaliação combinada precisa do detector.

In [3]:
PREFERRED_DETECTOR = WORKSPACE / 'runs' / 'path_A_5cls' / 'yolov11m_o2o' / 'weights' / 'best.pt'
PATH_A_RUN_DIRS = [
    WORKSPACE / 'runs' / 'path_A_5cls',
    WORKSPACE / 'runs' / 'path_A',
    WORKSPACE / 'runs' / 'path_A_refined_head',
]


def read_yolo_results(run_dir: Path):
    best_pt = run_dir / 'weights' / 'best.pt'
    results_csv = run_dir / 'results.csv'
    metrics_json = run_dir / 'metrics.json'

    if not best_pt.exists():
        return None

    row = {
        'group': run_dir.parent.name,
        'model': run_dir.name,
        'run_dir': run_dir,
        'best_pt': best_pt,
        'mAP50_95': None,
        'mAP50': None,
        'precision': None,
        'recall': None,
        'source': None,
    }

    if results_csv.exists():
        df = pd.read_csv(results_csv)
        df.columns = [c.strip() for c in df.columns]
        map95_col = 'metrics/mAP50-95(B)'
        map50_col = 'metrics/mAP50(B)'
        precision_col = 'metrics/precision(B)'
        recall_col = 'metrics/recall(B)'

        if map95_col in df.columns:
            best_idx = df[map95_col].idxmax()
        elif map50_col in df.columns:
            best_idx = df[map50_col].idxmax()
        else:
            best_idx = df.index[-1]

        best = df.loc[best_idx]
        row['mAP50_95'] = float(best[map95_col]) if map95_col in df.columns else None
        row['mAP50'] = float(best[map50_col]) if map50_col in df.columns else None
        row['precision'] = float(best[precision_col]) if precision_col in df.columns else None
        row['recall'] = float(best[recall_col]) if recall_col in df.columns else None
        row['source'] = 'results.csv'
        return row

    if metrics_json.exists():
        with open(metrics_json, 'r') as f:
            m = json.load(f)
        row['mAP50_95'] = m.get('mAP50_95')
        row['mAP50'] = m.get('mAP50')
        row['precision'] = m.get('precision')
        row['recall'] = m.get('recall')
        row['source'] = 'metrics.json'
        return row

    row['source'] = 'weights_only'
    return row


if PREFERRED_DETECTOR.exists():
    DETECTOR_WEIGHTS = PREFERRED_DETECTOR
    print('Usando detector preferido:', DETECTOR_WEIGHTS)
else:
    records = []
    for base_dir in PATH_A_RUN_DIRS:
        if not base_dir.exists():
            print(f'[warn] Pasta não encontrada: {base_dir}')
            continue
        for run_dir in sorted(base_dir.iterdir()):
            if run_dir.is_dir():
                rec = read_yolo_results(run_dir)
                if rec is not None:
                    records.append(rec)

    df_detectors = pd.DataFrame(records)
    if df_detectors.empty:
        raise FileNotFoundError(
            'Nenhum detector com weights/best.pt foi encontrado em: '
            + ', '.join(str(p) for p in PATH_A_RUN_DIRS)
        )

    df_ranked = df_detectors.copy()
    df_ranked['rank_score'] = df_ranked['mAP50_95'].fillna(df_ranked['mAP50']).fillna(-1)
    df_ranked = df_ranked.sort_values(
        by=['rank_score', 'mAP50', 'precision', 'recall'],
        ascending=False,
        na_position='last',
    ).reset_index(drop=True)

    display(df_ranked[['group', 'model', 'mAP50_95', 'mAP50', 'precision', 'recall', 'source', 'best_pt']])
    DETECTOR_WEIGHTS = Path(df_ranked.iloc[0]['best_pt'])
    print('Melhor detector encontrado:', DETECTOR_WEIGHTS)

if not DETECTOR_WEIGHTS.exists():
    raise FileNotFoundError(f'Detector não encontrado: {DETECTOR_WEIGHTS}')

Usando detector preferido: /workspace/runs/path_A_5cls/yolov11m_o2o/weights/best.pt

## 2) Pré-processamento dedicado do Path B

Esta etapa prepara os dados do Path B a partir do merged_data em `/workspace/processed_5cls/merged_data`,
gerando `images`, `labels`, `crops` e `dataset_path_B.yaml` dentro do root `/workspace/processed_5cls`.

A célula abaixo é idempotente: se a estrutura `train/val/test/path_B/{images,labels,crops}` e o YAML já existirem, ela só reutiliza o dataset. Para recriar o pré-processamento manualmente, altere `FORCE_PREPROCESS_PATH_B` para `True`.

In [4]:
# Pré-processamento do Path B a partir do merged_data. Rode uma vez; os outros treinos GT reutilizam o mesmo root.
FORCE_PREPROCESS_PATH_B = False

PREPROCESS_PATH_B_SCRIPT = DATA_DIR / 'preprocess.py'
MERGED_ROOT = PROCESSED_DIR / 'merged_data'
REQUIRED_PATH_B_ITEMS = [DATASET_YAML_PATH_B]

for split in ['train', 'val', 'test']:
    for subdir in ['images', 'labels', 'crops']:
        REQUIRED_PATH_B_ITEMS.append(PROCESSED_DIR / split / 'path_B' / subdir)

missing_path_b_items = [p for p in REQUIRED_PATH_B_ITEMS if not p.exists()]

if FORCE_PREPROCESS_PATH_B or missing_path_b_items:
    if FORCE_PREPROCESS_PATH_B:
        print('FORCE_PREPROCESS_PATH_B=True; executando pré-processamento do Path B.')
    else:
        print('Pré-processamento do Path B ausente ou incompleto. Itens faltantes:')
        for p in missing_path_b_items:
            print(' -', p)

    if not MERGED_ROOT.exists():
        raise FileNotFoundError(f'merged_data não encontrado: {MERGED_ROOT}')
    if not PREPROCESS_PATH_B_SCRIPT.exists():
        raise FileNotFoundError(f'Script de pré-processamento não encontrado: {PREPROCESS_PATH_B_SCRIPT}')

    run_cmd([
        sys.executable, str(PREPROCESS_PATH_B_SCRIPT),
        '--taco_root', str(MERGED_ROOT),
        '--output_root', str(PROCESSED_DIR),
        '--path', 'B',
    ])
else:
    print('Pré-processamento do Path B já encontrado:', PROCESSED_DIR)

Pré-processamento do Path B já encontrado: /workspace/processed_5cls

## 3) Conferir crops GT

Este notebook treina em `CropDataset`, então ele depende de `train/val/test/path_B/crops/{class_idx}`.

In [5]:
for split in ['train', 'val', 'test']:
    crop_root = PROCESSED_DIR / split / 'path_B' / 'crops'
    if not crop_root.exists():
        raise FileNotFoundError(f'Crops GT não encontrados: {crop_root}')

    counts = {}
    for cls_dir in sorted(crop_root.iterdir()):
        if cls_dir.is_dir():
            counts[cls_dir.name] = len(list(cls_dir.glob('*.jpg')))

    print(split, crop_root)
    print('  total:', sum(counts.values()), 'por classe:', counts)

train /workspace/processed_5cls/train/path_B/crops
  total: 15678 por classe: {'0': 6025, '1': 1307, '2': 1245, '3': 500, '4': 6601}
val /workspace/processed_5cls/val/path_B/crops
  total: 3447 por classe: {'0': 1411, '1': 267, '2': 282, '3': 107, '4': 1380}
test /workspace/processed_5cls/test/path_B/crops
  total: 3208 por classe: {'0': 1312, '1': 280, '2': 265, '3': 88, '4': 1263}

## 4) Treinos em GT crops (B1, B3, B4)

Sem `--use_yolo_crops`. O classificador é treinado nos crops GT pré-gerados.
Parâmetros fixos: epochs=300, batch=8, patience=15.

In [16]:
print('---', B1['label'], '---')
print('Parâmetros de treino:')
print('Detector weights:', DETECTOR_WEIGHTS)
print('Crops dir:', PROCESSED_DIR)
print('Output dir:', B1['run_dir'])
print('Classifier:', B1['classifier'])
print('Epochs:', EPOCHS)
print('Batch:', BATCH)
print('Learning rate:', LR)
print('Patience:', PATIENCE)
print('Device:', DEVICE)
print('Use YOLO crops:', False)

run_cmd([
    sys.executable, str(TRAIN_PATH_B_SCRIPT),
    '--detector_weights', str(DETECTOR_WEIGHTS),
    '--crops_dir', str(PROCESSED_DIR),
    '--output', str(B1['run_dir']),
    '--classifiers', B1['classifier'],
    '--epochs', str(EPOCHS),
    '--batch', str(BATCH),
    '--lr', str(LR),
    '--patience', str(PATIENCE),
    '--device', str(DEVICE),
])

--- B1 (resnet50) ---
Parâmetros de treino:
Detector weights: /workspace/runs/path_A_5cls/yolov11m_o2o/weights/best.pt
Crops dir: /workspace/processed_5cls
Output dir: /workspace/runs/path_B_gt_b1
Classifier: resnet50
Epochs: 300
Batch: 8
Learning rate: 5e-05
Patience: 15
Device: 0
Use YOLO crops: False
$ /workspace/.venv/bin/python /workspace/TrashScan/train/paths/train_path_B.py --detector_weights /workspace/runs/path_A_5cls/yolov11m_o2o/weights/best.pt --crops_dir /workspace/processed_5cls --output /workspace/runs/path_B_gt_b1 --classifiers resnet50 --epochs 300 --batch 8 --lr 5e-05 --patience 15 --device 0
Device : cuda:0
GPU    : NVIDIA RTX 4000 Ada Generation  VRAM: 21.1GB
Class weights: {'plastic': 0.511, 'paper': 1.098, 'metal': 1.125, 'glass': 1.777, 'other': 0.489}

  Mode: loading pre-generated GT crops from disk
  [train] 15678 GT crops across 5 classes
  [val] 3447 GT crops across 5 classes
  [test] 3208 GT crops across 5 classes

────────────────────────────────────────────────────────────
  Classifier : resnet50
────────────────────────────────────────────────────────────

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

  Built resnet50 (resnet50.a1_in1k)  pretrained=True  23.5M params

  Ep   1/300 | train loss=1.3451 acc=0.5691 | val loss=1.0583 acc=0.6194 f1=0.2738

  Ep   2/300 | train loss=1.1877 acc=0.6309 | val loss=0.9248 acc=0.6916 f1=0.4729

  Ep   3/300 | train loss=1.0653 acc=0.6551 | val loss=0.8465 acc=0.6951 f1=0.5355

  Ep   4/300 | train loss=0.9860 acc=0.6696 | val loss=0.7562 acc=0.7140 f1=0.5691

  Ep   5/300 | train loss=0.9176 acc=0.6915 | val loss=0.6963 acc=0.7386 f1=0.6183

  Ep   6/300 | train loss=0.8542 acc=0.7085 | val loss=0.6913 acc=0.7456 f1=0.6606

  Ep   7/300 | train loss=0.8060 acc=0.7228 | val loss=0.6586 acc=0.7583 f1=0.6677

  Ep 9/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep   8/300 | train loss=0.7617 acc=0.7411 | val loss=0.6550 acc=0.7572 f1=0.6783

  Ep   9/300 | train loss=0.7336 acc=0.7489 | val loss=0.6008 acc=0.7743 f1=0.7028

  Ep 11/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  10/300 | train loss=0.6923 acc=0.7618 | val loss=0.6228 acc=0.7728 f1=0.7043

  Ep  11/300 | train loss=0.6697 acc=0.7669 | val loss=0.5729 acc=0.7888 f1=0.7232

  Ep 13/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  12/300 | train loss=0.6427 acc=0.7782 | val loss=0.5875 acc=0.7821 f1=0.7105

  Ep  13/300 | train loss=0.6162 acc=0.7842 | val loss=0.5685 acc=0.7934 f1=0.7275

  Ep  14/300 | train loss=0.5789 acc=0.8002 | val loss=0.5555 acc=0.8007 f1=0.7321

  Ep 16/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  15/300 | train loss=0.5625 acc=0.8025 | val loss=0.5669 acc=0.7969 f1=0.7471

  Ep 17/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  16/300 | train loss=0.5455 acc=0.8069 | val loss=0.5576 acc=0.8007 f1=0.7480

  Ep  17/300 | train loss=0.5309 acc=0.8157 | val loss=0.5409 acc=0.8117 f1=0.7558

  Ep 19/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  18/300 | train loss=0.5033 acc=0.8244 | val loss=0.5713 acc=0.8094 f1=0.7538

  Ep 20/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  19/300 | train loss=0.4856 acc=0.8291 | val loss=0.5779 acc=0.8039 f1=0.7588

  Ep  20/300 | train loss=0.4590 acc=0.8350 | val loss=0.5270 acc=0.8181 f1=0.7735

  Ep 22/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  21/300 | train loss=0.4521 acc=0.8416 | val loss=0.5533 acc=0.8161 f1=0.7739

  Ep  22/300 | train loss=0.4376 acc=0.8476 | val loss=0.5375 acc=0.8227 f1=0.7843

  Ep 24/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  23/300 | train loss=0.4225 acc=0.8487 | val loss=0.5452 acc=0.8216 f1=0.7803

  Ep 25/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  24/300 | train loss=0.3983 acc=0.8569 | val loss=0.5809 acc=0.8111 f1=0.7685

  Ep  25/300 | train loss=0.3912 acc=0.8613 | val loss=0.5447 acc=0.8256 f1=0.7825

  Ep 27/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  26/300 | train loss=0.3740 acc=0.8667 | val loss=0.5670 acc=0.8227 f1=0.7912

  Ep  27/300 | train loss=0.3667 acc=0.8682 | val loss=0.5586 acc=0.8274 f1=0.7924

  Ep  28/300 | train loss=0.3536 acc=0.8721 | val loss=0.5503 acc=0.8317 f1=0.7927

  Ep 30/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  29/300 | train loss=0.3380 acc=0.8794 | val loss=0.5474 acc=0.8256 f1=0.7917

  Ep  30/300 | train loss=0.3289 acc=0.8812 | val loss=0.5487 acc=0.8343 f1=0.8019

  Ep 32/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  31/300 | train loss=0.3168 acc=0.8881 | val loss=0.5701 acc=0.8329 f1=0.8004

  Ep 33/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  32/300 | train loss=0.3097 acc=0.8851 | val loss=0.5566 acc=0.8317 f1=0.8078

  Ep  33/300 | train loss=0.3028 acc=0.8926 | val loss=0.5315 acc=0.8352 f1=0.8050

  Ep 35/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  34/300 | train loss=0.2975 acc=0.8927 | val loss=0.5821 acc=0.8283 f1=0.7928

  Ep 36/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  35/300 | train loss=0.2866 acc=0.8964 | val loss=0.5629 acc=0.8329 f1=0.8007

  Ep  36/300 | train loss=0.2739 acc=0.8986 | val loss=0.5773 acc=0.8396 f1=0.8151

  Ep  37/300 | train loss=0.2704 acc=0.8995 | val loss=0.5703 acc=0.8407 f1=0.8224

  Ep 39/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  38/300 | train loss=0.2511 acc=0.9091 | val loss=0.6219 acc=0.8326 f1=0.8104

  Ep 40/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  39/300 | train loss=0.2550 acc=0.9060 | val loss=0.5975 acc=0.8349 f1=0.8091

  Ep 41/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  40/300 | train loss=0.2508 acc=0.9086 | val loss=0.6071 acc=0.8346 f1=0.8085

  Ep 42/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  41/300 | train loss=0.2373 acc=0.9124 | val loss=0.6192 acc=0.8370 f1=0.8073

  Ep 43/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  42/300 | train loss=0.2380 acc=0.9129 | val loss=0.6352 acc=0.8320 f1=0.8068

  Ep 44/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  43/300 | train loss=0.2282 acc=0.9167 | val loss=0.6347 acc=0.8361 f1=0.8064

  Ep 45/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  44/300 | train loss=0.2139 acc=0.9208 | val loss=0.6717 acc=0.8390 f1=0.8158

  Ep 46/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  45/300 | train loss=0.2192 acc=0.9207 | val loss=0.6464 acc=0.8375 f1=0.8072

  Ep 47/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  46/300 | train loss=0.2149 acc=0.9203 | val loss=0.6739 acc=0.8361 f1=0.8047

  Ep 48/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  47/300 | train loss=0.2088 acc=0.9227 | val loss=0.6414 acc=0.8349 f1=0.8132

  Ep 49/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  48/300 | train loss=0.1990 acc=0.9270 | val loss=0.6423 acc=0.8402 f1=0.8172

  Ep  49/300 | train loss=0.1972 acc=0.9275 | val loss=0.6659 acc=0.8422 f1=0.8180

  Ep 51/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  50/300 | train loss=0.1929 acc=0.9293 | val loss=0.6361 acc=0.8402 f1=0.8150

  Ep  51/300 | train loss=0.1896 acc=0.9305 | val loss=0.6614 acc=0.8445 f1=0.8226

  Ep 53/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  52/300 | train loss=0.1851 acc=0.9317 | val loss=0.6549 acc=0.8422 f1=0.8175

  Ep  53/300 | train loss=0.1837 acc=0.9332 | val loss=0.6250 acc=0.8552 f1=0.8394

  Ep 55/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  54/300 | train loss=0.1759 acc=0.9369 | val loss=0.6846 acc=0.8422 f1=0.8117

  Ep 56/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  55/300 | train loss=0.1734 acc=0.9345 | val loss=0.6589 acc=0.8471 f1=0.8278

  Ep 57/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  56/300 | train loss=0.1682 acc=0.9387 | val loss=0.6563 acc=0.8471 f1=0.8275

  Ep 58/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  57/300 | train loss=0.1664 acc=0.9387 | val loss=0.6578 acc=0.8477 f1=0.8147

  Ep  58/300 | train loss=0.1611 acc=0.9391 | val loss=0.6512 acc=0.8393 f1=0.8187

  Ep 60/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  59/300 | train loss=0.1612 acc=0.9404 | val loss=0.6690 acc=0.8460 f1=0.8192

  Ep 61/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  60/300 | train loss=0.1472 acc=0.9461 | val loss=0.6812 acc=0.8515 f1=0.8271

  Ep 62/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  61/300 | train loss=0.1498 acc=0.9462 | val loss=0.6940 acc=0.8436 f1=0.8197

  Ep 63/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  62/300 | train loss=0.1469 acc=0.9451 | val loss=0.6954 acc=0.8402 f1=0.8217

  Ep 64/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  63/300 | train loss=0.1427 acc=0.9470 | val loss=0.6906 acc=0.8474 f1=0.8281

  Ep 65/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  64/300 | train loss=0.1416 acc=0.9489 | val loss=0.6907 acc=0.8465 f1=0.8232

  Ep 66/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  65/300 | train loss=0.1369 acc=0.9494 | val loss=0.7230 acc=0.8518 f1=0.8289

  Ep  66/300 | train loss=0.1389 acc=0.9501 | val loss=0.6868 acc=0.8558 f1=0.8312

  Ep 68/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  67/300 | train loss=0.1324 acc=0.9515 | val loss=0.7027 acc=0.8497 f1=0.8262

  Ep 69/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  68/300 | train loss=0.1343 acc=0.9508 | val loss=0.7075 acc=0.8503 f1=0.8315

  Ep 70/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  69/300 | train loss=0.1320 acc=0.9538 | val loss=0.7041 acc=0.8491 f1=0.8369

  Ep 71/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  70/300 | train loss=0.1263 acc=0.9553 | val loss=0.7295 acc=0.8506 f1=0.8259

  Ep 72/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  71/300 | train loss=0.1217 acc=0.9546 | val loss=0.7596 acc=0.8477 f1=0.8300

  Ep 73/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  72/300 | train loss=0.1242 acc=0.9550 | val loss=0.7281 acc=0.8515 f1=0.8285

  Ep 74/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  73/300 | train loss=0.1241 acc=0.9546 | val loss=0.7208 acc=0.8547 f1=0.8382

  Ep 75/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  74/300 | train loss=0.1170 acc=0.9578 | val loss=0.7351 acc=0.8520 f1=0.8349

  Ep  75/300 | train loss=0.1172 acc=0.9583 | val loss=0.7347 acc=0.8581 f1=0.8433

  Ep 77/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  76/300 | train loss=0.1090 acc=0.9605 | val loss=0.7642 acc=0.8544 f1=0.8332

  Ep 78/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  77/300 | train loss=0.1077 acc=0.9606 | val loss=0.7214 acc=0.8515 f1=0.8305

  Ep 79/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  78/300 | train loss=0.1071 acc=0.9602 | val loss=0.7639 acc=0.8520 f1=0.8301

  Ep 80/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  79/300 | train loss=0.1125 acc=0.9584 | val loss=0.7779 acc=0.8468 f1=0.8251

  Ep  80/300 | train loss=0.1037 acc=0.9608 | val loss=0.7055 acc=0.8596 f1=0.8345

  Ep  81/300 | train loss=0.1039 acc=0.9620 | val loss=0.7024 acc=0.8622 f1=0.8417

  Ep 83/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  82/300 | train loss=0.1047 acc=0.9633 | val loss=0.7301 acc=0.8599 f1=0.8363

  Ep 84/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  83/300 | train loss=0.0973 acc=0.9656 | val loss=0.7926 acc=0.8590 f1=0.8455

  Ep 85/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  84/300 | train loss=0.0981 acc=0.9649 | val loss=0.7757 acc=0.8555 f1=0.8358

  Ep 86/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  85/300 | train loss=0.1008 acc=0.9633 | val loss=0.7453 acc=0.8564 f1=0.8364

  Ep 87/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  86/300 | train loss=0.0960 acc=0.9657 | val loss=0.7675 acc=0.8520 f1=0.8297

  Ep 88/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  87/300 | train loss=0.0898 acc=0.9666 | val loss=0.7787 acc=0.8489 f1=0.8241

  Ep 89/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  88/300 | train loss=0.0926 acc=0.9673 | val loss=0.7751 acc=0.8578 f1=0.8378

  Ep 90/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  89/300 | train loss=0.0902 acc=0.9673 | val loss=0.7622 acc=0.8552 f1=0.8367

  Ep 91/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  90/300 | train loss=0.0897 acc=0.9680 | val loss=0.8468 acc=0.8520 f1=0.8310

  Ep 92/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  91/300 | train loss=0.0851 acc=0.9680 | val loss=0.7726 acc=0.8561 f1=0.8390

  Ep 93/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  92/300 | train loss=0.0879 acc=0.9681 | val loss=0.7870 acc=0.8590 f1=0.8402

  Ep 94/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  93/300 | train loss=0.0853 acc=0.9707 | val loss=0.7731 acc=0.8520 f1=0.8344

  Ep  94/300 | train loss=0.0836 acc=0.9705 | val loss=0.7929 acc=0.8465 f1=0.8210

  Ep 96/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  95/300 | train loss=0.0785 acc=0.9701 | val loss=0.7658 acc=0.8564 f1=0.8382

  Ep  96/300 | train loss=0.0848 acc=0.9700 | val loss=0.8107 acc=0.8573 f1=0.8367
  Early stopping at epoch 96 (best epoch 81, val_acc=0.8622)

  Test: 100%|██████████| 401/401 [00:08<00:00, 46.46it/s]

  [resnet50]  accuracy=0.8809  f1=0.8524  latency=7.00ms

  [resnet50]  best_epoch=81  val_acc=0.8622  test_acc=0.8809  f1=0.8524

======================================================================
PATH B  —  CLASSIFIER BENCHMARK SUMMARY
======================================================================
            accuracy  precision  recall     f1  latency_ms  AP_plastic  AP_paper  AP_metal  AP_glass  AP_other
classifier
resnet50      0.8809     0.8352  0.8738 0.8524      7.0020      0.9574    0.8884    0.8766    0.8629    0.9555
======================================================================

CompletedProcess(args=['/workspace/.venv/bin/python', '/workspace/TrashScan/train/paths/train_path_B.py', '--detector_weights', '/workspace/runs/path_A_5cls/yolov11m_o2o/weights/best.pt', '--crops_dir', '/workspace/processed_5cls', '--output', '/workspace/runs/path_B_gt_b1', '--classifiers', 'resnet50', '--epochs', '300', '--batch', '8', '--lr', '5e-05', '--patience', '15', '--device', '0'], returncode=0)

In [11]:
print('---', B3['label'], '---')
print('Parâmetros de treino:')
print('Detector weights:', DETECTOR_WEIGHTS)
print('Crops dir:', PROCESSED_DIR)
print('Output dir:', B3['run_dir'])
print('Classifier:', B3['classifier'])
print('Epochs:', EPOCHS)
print('Batch:', BATCH)
print('Learning rate:', LR)
print('Patience:', PATIENCE)
print('Device:', DEVICE)
print('Use YOLO crops:', False)

run_cmd([
    sys.executable, str(TRAIN_PATH_B_SCRIPT),
    '--detector_weights', str(DETECTOR_WEIGHTS),
    '--crops_dir', str(PROCESSED_DIR),
    '--output', str(B3['run_dir']),
    '--classifiers', B3['classifier'],
    '--epochs', str(EPOCHS),
    '--batch', str(BATCH),
    '--lr', str(LR),
    '--patience', str(PATIENCE),
    '--device', str(DEVICE),
])

--- B3 (vit_b16_imagenet) ---
Parâmetros de treino:
Detector weights: /workspace/runs/path_A_5cls/yolov11m_o2o/weights/best.pt
Crops dir: /workspace/processed_5cls
Output dir: /workspace/runs/path_B_gt_b3
Classifier: vit_b16_imagenet
Epochs: 300
Batch: 8
Learning rate: 5e-05
Patience: 15
Device: 0
Use YOLO crops: False
$ /workspace/.venv/bin/python /workspace/TrashScan/train/paths/train_path_B.py --detector_weights /workspace/runs/path_A_5cls/yolov11m_o2o/weights/best.pt --crops_dir /workspace/processed_5cls --output /workspace/runs/path_B_gt_b3 --classifiers vit_b16_imagenet --epochs 300 --batch 8 --lr 5e-05 --patience 15 --device 0

Device : cuda:0
GPU    : NVIDIA RTX 4000 Ada Generation  VRAM: 21.1GB
Class weights: {'plastic': 0.511, 'paper': 1.098, 'metal': 1.125, 'glass': 1.777, 'other': 0.489}

  Mode: loading pre-generated GT crops from disk
  [train] 15678 GT crops across 5 classes
  [val] 3447 GT crops across 5 classes
  [test] 3208 GT crops across 5 classes

────────────────────────────────────────────────────────────
  Classifier : vit_b16_imagenet
────────────────────────────────────────────────────────────
  Built vit_b16_imagenet (vit_base_patch16_224.augreg_in21k_ft_in1k)  pretrained=True  85.8M params

  Ep   1/300 | train loss=0.9638 acc=0.6896 | val loss=0.7036 acc=0.7325 f1=0.6394

  Ep   2/300 | train loss=0.6953 acc=0.7685 | val loss=0.5827 acc=0.7818 f1=0.7187

  Ep   3/300 | train loss=0.5879 acc=0.7991 | val loss=0.5843 acc=0.7961 f1=0.7141

  Ep   4/300 | train loss=0.4963 acc=0.8275 | val loss=0.5726 acc=0.8036 f1=0.7257

  Ep   5/300 | train loss=0.4377 acc=0.8458 | val loss=0.5084 acc=0.8132 f1=0.7560

  Ep   6/300 | train loss=0.3856 acc=0.8617 | val loss=0.4908 acc=0.8367 f1=0.7934

  Ep 8/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep   7/300 | train loss=0.3509 acc=0.8778 | val loss=0.4999 acc=0.8352 f1=0.7948

  Ep 9/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep   8/300 | train loss=0.3204 acc=0.8868 | val loss=0.4809 acc=0.8352 f1=0.8111

  Ep   9/300 | train loss=0.2780 acc=0.8996 | val loss=0.4449 acc=0.8483 f1=0.8154

  Ep 11/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  10/300 | train loss=0.2639 acc=0.9041 | val loss=0.6162 acc=0.8126 f1=0.7581

  Ep 12/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  11/300 | train loss=0.2389 acc=0.9110 | val loss=0.5319 acc=0.8358 f1=0.8099

  Ep  12/300 | train loss=0.2297 acc=0.9176 | val loss=0.4508 acc=0.8605 f1=0.8352

  Ep 14/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  13/300 | train loss=0.2130 acc=0.9237 | val loss=0.5031 acc=0.8599 f1=0.8436

  Ep 15/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  14/300 | train loss=0.2110 acc=0.9226 | val loss=0.5366 acc=0.8561 f1=0.8317

  Ep 16/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  15/300 | train loss=0.1955 acc=0.9282 | val loss=0.5839 acc=0.8428 f1=0.8203

  Ep 17/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  16/300 | train loss=0.1806 acc=0.9333 | val loss=0.4983 acc=0.8552 f1=0.8396

  Ep 18/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  17/300 | train loss=0.1726 acc=0.9380 | val loss=0.5404 acc=0.8471 f1=0.8090

  Ep  18/300 | train loss=0.1707 acc=0.9378 | val loss=0.4876 acc=0.8660 f1=0.8458

  Ep 20/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  19/300 | train loss=0.1606 acc=0.9435 | val loss=0.5264 acc=0.8555 f1=0.8249

  Ep  20/300 | train loss=0.1574 acc=0.9439 | val loss=0.4734 acc=0.8715 f1=0.8602

  Ep 22/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  21/300 | train loss=0.1480 acc=0.9465 | val loss=0.5125 acc=0.8509 f1=0.8214

  Ep 23/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  22/300 | train loss=0.1418 acc=0.9477 | val loss=0.5180 acc=0.8544 f1=0.8273

  Ep 24/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  23/300 | train loss=0.1377 acc=0.9470 | val loss=0.5626 acc=0.8628 f1=0.8465

  Ep 25/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  24/300 | train loss=0.1344 acc=0.9512 | val loss=0.5470 acc=0.8518 f1=0.8146

  Ep 26/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  25/300 | train loss=0.1438 acc=0.9489 | val loss=0.5857 acc=0.8439 f1=0.7929

  Ep 27/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  26/300 | train loss=0.1258 acc=0.9564 | val loss=0.5271 acc=0.8607 f1=0.8267

  Ep 28/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  27/300 | train loss=0.1271 acc=0.9548 | val loss=0.4956 acc=0.8639 f1=0.8425

  Ep 29/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  28/300 | train loss=0.1166 acc=0.9580 | val loss=0.6096 acc=0.8689 f1=0.8521

  Ep 30/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  29/300 | train loss=0.1158 acc=0.9597 | val loss=0.5320 acc=0.8692 f1=0.8447

  Ep 31/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  30/300 | train loss=0.1246 acc=0.9549 | val loss=0.5378 acc=0.8651 f1=0.8369

  Ep 32/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  31/300 | train loss=0.1076 acc=0.9625 | val loss=0.5684 acc=0.8520 f1=0.8233

  Ep 33/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  32/300 | train loss=0.1095 acc=0.9586 | val loss=0.6093 acc=0.8602 f1=0.8249

  Ep  33/300 | train loss=0.1159 acc=0.9603 | val loss=0.5132 acc=0.8773 f1=0.8630

  Ep 35/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  34/300 | train loss=0.0988 acc=0.9624 | val loss=0.5882 acc=0.8718 f1=0.8579

  Ep 36/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  35/300 | train loss=0.0998 acc=0.9653 | val loss=0.5664 acc=0.8642 f1=0.8449

  Ep 37/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  36/300 | train loss=0.1053 acc=0.9624 | val loss=0.5066 acc=0.8715 f1=0.8607

  Ep  37/300 | train loss=0.0974 acc=0.9651 | val loss=0.5800 acc=0.8782 f1=0.8653

  Ep 39/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  38/300 | train loss=0.1000 acc=0.9631 | val loss=0.4862 acc=0.8680 f1=0.8365

  Ep 40/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  39/300 | train loss=0.1026 acc=0.9639 | val loss=0.6140 acc=0.8254 f1=0.7834

  Ep 41/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  40/300 | train loss=0.0967 acc=0.9667 | val loss=0.4965 acc=0.8758 f1=0.8539

  Ep 42/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  41/300 | train loss=0.0879 acc=0.9685 | val loss=0.6333 acc=0.8697 f1=0.8397

  Ep 43/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  42/300 | train loss=0.0899 acc=0.9695 | val loss=0.5513 acc=0.8668 f1=0.8502

  Ep 44/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  43/300 | train loss=0.0814 acc=0.9707 | val loss=0.6019 acc=0.8616 f1=0.8341

  Ep 45/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  44/300 | train loss=0.0956 acc=0.9662 | val loss=0.5344 acc=0.8648 f1=0.8424

  Ep 46/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  45/300 | train loss=0.0853 acc=0.9696 | val loss=0.5711 acc=0.8779 f1=0.8652

  Ep 47/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  46/300 | train loss=0.0820 acc=0.9696 | val loss=0.6496 acc=0.8518 f1=0.8172

  Ep 48/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  47/300 | train loss=0.0827 acc=0.9703 | val loss=0.7221 acc=0.8607 f1=0.8184

  Ep 49/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  48/300 | train loss=0.0890 acc=0.9686 | val loss=0.6392 acc=0.8668 f1=0.8418

  Ep 50/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  49/300 | train loss=0.0795 acc=0.9709 | val loss=0.5943 acc=0.8602 f1=0.8362

  Ep 51/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  50/300 | train loss=0.0772 acc=0.9716 | val loss=0.6029 acc=0.8738 f1=0.8610

  Ep  51/300 | train loss=0.0814 acc=0.9733 | val loss=0.6072 acc=0.8790 f1=0.8623

  Ep 53/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  52/300 | train loss=0.0752 acc=0.9732 | val loss=0.6504 acc=0.8666 f1=0.8462

  Ep 54/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  53/300 | train loss=0.0822 acc=0.9714 | val loss=0.6065 acc=0.8782 f1=0.8710

  Ep 55/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  54/300 | train loss=0.0766 acc=0.9743 | val loss=0.6123 acc=0.8462 f1=0.7940

  Ep 56/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  55/300 | train loss=0.0710 acc=0.9761 | val loss=0.5949 acc=0.8703 f1=0.8518

  Ep 57/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  56/300 | train loss=0.0713 acc=0.9738 | val loss=0.5926 acc=0.8761 f1=0.8671

  Ep 58/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  57/300 | train loss=0.0732 acc=0.9742 | val loss=0.5735 acc=0.8706 f1=0.8509

  Ep 59/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  58/300 | train loss=0.0733 acc=0.9753 | val loss=0.5591 acc=0.8747 f1=0.8561

  Ep 60/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  59/300 | train loss=0.0609 acc=0.9775 | val loss=0.6068 acc=0.8784 f1=0.8674

  Ep 61/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  60/300 | train loss=0.0717 acc=0.9740 | val loss=0.5738 acc=0.8735 f1=0.8526

  Ep 62/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  61/300 | train loss=0.0658 acc=0.9761 | val loss=0.6433 acc=0.8651 f1=0.8363

  Ep 63/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  62/300 | train loss=0.0672 acc=0.9758 | val loss=0.6006 acc=0.8715 f1=0.8482

  Ep 64/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  63/300 | train loss=0.0689 acc=0.9763 | val loss=0.6272 acc=0.8619 f1=0.8335

  Ep 65/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  64/300 | train loss=0.0643 acc=0.9786 | val loss=0.5538 acc=0.8709 f1=0.8460

  Ep 66/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  65/300 | train loss=0.0593 acc=0.9791 | val loss=0.6143 acc=0.8776 f1=0.8680

  Ep  66/300 | train loss=0.0633 acc=0.9791 | val loss=0.5581 acc=0.8877 f1=0.8764

  Ep 68/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  67/300 | train loss=0.0573 acc=0.9796 | val loss=0.6413 acc=0.8642 f1=0.8496

  Ep 69/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  68/300 | train loss=0.0615 acc=0.9798 | val loss=0.5518 acc=0.8761 f1=0.8606

  Ep 70/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  69/300 | train loss=0.0669 acc=0.9781 | val loss=0.6217 acc=0.8709 f1=0.8507

  Ep 71/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  70/300 | train loss=0.0526 acc=0.9820 | val loss=0.5671 acc=0.8735 f1=0.8627

  Ep 72/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  71/300 | train loss=0.0533 acc=0.9820 | val loss=0.6588 acc=0.8735 f1=0.8564

  Ep 73/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  72/300 | train loss=0.0545 acc=0.9810 | val loss=0.6252 acc=0.8805 f1=0.8683

  Ep 74/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  73/300 | train loss=0.0520 acc=0.9826 | val loss=0.6987 acc=0.8718 f1=0.8513

  Ep 75/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  74/300 | train loss=0.0546 acc=0.9814 | val loss=0.6506 acc=0.8677 f1=0.8564

  Ep 76/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  75/300 | train loss=0.0518 acc=0.9827 | val loss=0.5797 acc=0.8744 f1=0.8546

  Ep 77/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  76/300 | train loss=0.0579 acc=0.9801 | val loss=0.6212 acc=0.8744 f1=0.8518

  Ep 78/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  77/300 | train loss=0.0456 acc=0.9828 | val loss=0.6580 acc=0.8828 f1=0.8679

  Ep 79/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  78/300 | train loss=0.0457 acc=0.9838 | val loss=0.6468 acc=0.8796 f1=0.8654

  Ep 80/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  79/300 | train loss=0.0527 acc=0.9820 | val loss=0.6114 acc=0.8793 f1=0.8569

  Ep 81/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  80/300 | train loss=0.0489 acc=0.9814 | val loss=0.6638 acc=0.8776 f1=0.8594

  Ep  81/300 | train loss=0.0488 acc=0.9830 | val loss=0.6388 acc=0.8726 f1=0.8441
  Early stopping at epoch 81 (best epoch 66, val_acc=0.8877)

  Test: 100%|██████████| 401/401 [00:12<00:00, 31.48it/s]

  [vit_b16_imagenet]  accuracy=0.8937  f1=0.8825  latency=5.22ms

  [vit_b16_imagenet]  best_epoch=66  val_acc=0.8877  test_acc=0.8937  f1=0.8825

======================================================================
PATH B  —  CLASSIFIER BENCHMARK SUMMARY
======================================================================
                  accuracy  precision  recall     f1  latency_ms  AP_plastic  AP_paper  AP_metal  AP_glass  AP_other
classifier
vit_b16_imagenet    0.8937     0.8792  0.8871 0.8825      5.2200      0.9609    0.9277    0.9279    0.8893    0.9651
======================================================================

CompletedProcess(args=['/workspace/.venv/bin/python', '/workspace/TrashScan/train/paths/train_path_B.py', '--detector_weights', '/workspace/runs/path_A_5cls/yolov11m_o2o/weights/best.pt', '--crops_dir', '/workspace/processed_5cls', '--output', '/workspace/runs/path_B_gt_b3', '--classifiers', 'vit_b16_imagenet', '--epochs', '300', '--batch', '8', '--lr', '5e-05', '--patience', '15', '--device', '0'], returncode=0)

In [8]:
print('---', B4['label'], '---')
print('Parâmetros de treino:')
print('Detector weights:', DETECTOR_WEIGHTS)
print('Crops dir:', PROCESSED_DIR)
print('Output dir:', B4['run_dir'])
print('Classifier:', B4['classifier'])
print('Epochs:', EPOCHS)
print('Batch:', BATCH)
print('Learning rate:', LR)
print('Patience:', PATIENCE)
print('Device:', DEVICE)
print('Use YOLO crops:', False)

run_cmd([
    sys.executable, str(TRAIN_PATH_B_SCRIPT),
    '--detector_weights', str(DETECTOR_WEIGHTS),
    '--crops_dir', str(PROCESSED_DIR),
    '--output', str(B4['run_dir']),
    '--classifiers', B4['classifier'],
    '--epochs', str(EPOCHS),
    '--batch', str(BATCH),
    '--lr', str(LR),
    '--patience', str(PATIENCE),
    '--device', str(DEVICE),
])

--- B4 (vit_l16_imagenet) ---
Parâmetros de treino:
Detector weights: /workspace/runs/path_A_5cls/yolov11m_o2o/weights/best.pt
Crops dir: /workspace/processed_5cls
Output dir: /workspace/runs/path_B_gt_b4
Classifier: vit_l16_imagenet
Epochs: 300
Batch: 8
Learning rate: 5e-05
Patience: 15
Device: 0
Use YOLO crops: False
TTA+WBF no treino: False
$ /workspace/.venv/bin/python /workspace/TrashScan/train/paths/train_path_B.py --detector_weights /workspace/runs/path_A_5cls/yolov11m_o2o/weights/best.pt --crops_dir /workspace/processed_5cls --output /workspace/runs/path_B_gt_b4 --classifiers vit_l16_imagenet --epochs 300 --batch 8 --lr 5e-05 --patience 15 --device 0

Device : cuda:0
GPU    : NVIDIA RTX 4000 Ada Generation  VRAM: 21.0GB
Class weights: {'plastic': 0.511, 'paper': 1.098, 'metal': 1.125, 'glass': 1.777, 'other': 0.489}

  Mode: loading pre-generated GT crops from disk
  [train] 15678 GT crops across 5 classes
  [val] 3447 GT crops across 5 classes
  [test] 3208 GT crops across 5 classes

────────────────────────────────────────────────────────────
  Classifier : vit_l16_imagenet
────────────────────────────────────────────────────────────

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

  Built vit_l16_imagenet (vit_large_patch16_224.augreg_in21k_ft_in1k)  pretrained=True  303.3M params

  Ep   1/300 | train loss=0.8311 acc=0.7282 | val loss=0.6572 acc=0.7514 f1=0.6987

  Ep   2/300 | train loss=0.5751 acc=0.8046 | val loss=0.5542 acc=0.8001 f1=0.7461

  Ep   3/300 | train loss=0.4301 acc=0.8499 | val loss=0.4537 acc=0.8410 f1=0.7950

  Ep   4/300 | train loss=0.3754 acc=0.8715 | val loss=0.4758 acc=0.8428 f1=0.7841

  Ep 6/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep   5/300 | train loss=0.3156 acc=0.8905 | val loss=0.4995 acc=0.8428 f1=0.8145

  Ep 7/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep   6/300 | train loss=0.2721 acc=0.9037 | val loss=0.4792 acc=0.8425 f1=0.7987

  Ep   7/300 | train loss=0.2499 acc=0.9120 | val loss=0.4646 acc=0.8590 f1=0.8314

  Ep   8/300 | train loss=0.2246 acc=0.9206 | val loss=0.4884 acc=0.8625 f1=0.8428

  Ep 10/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep   9/300 | train loss=0.2010 acc=0.9281 | val loss=0.4484 acc=0.8549 f1=0.8289

  Ep 11/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  10/300 | train loss=0.1889 acc=0.9326 | val loss=0.4771 acc=0.8515 f1=0.8275

  Ep  11/300 | train loss=0.1896 acc=0.9339 | val loss=0.4662 acc=0.8697 f1=0.8399

  Ep 13/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  12/300 | train loss=0.1689 acc=0.9407 | val loss=0.4705 acc=0.8686 f1=0.8452

  Ep  13/300 | train loss=0.1582 acc=0.9430 | val loss=0.4007 acc=0.8773 f1=0.8602

  Ep 15/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  14/300 | train loss=0.1507 acc=0.9493 | val loss=0.4899 acc=0.8628 f1=0.8309

  Ep 16/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  15/300 | train loss=0.1592 acc=0.9444 | val loss=0.4765 acc=0.8631 f1=0.8415

  Ep 17/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  16/300 | train loss=0.1452 acc=0.9495 | val loss=0.4780 acc=0.8660 f1=0.8453

  Ep 18/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  17/300 | train loss=0.1360 acc=0.9534 | val loss=0.4796 acc=0.8724 f1=0.8540

  Ep  18/300 | train loss=0.1362 acc=0.9526 | val loss=0.4577 acc=0.8776 f1=0.8634

  Ep 20/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  19/300 | train loss=0.1226 acc=0.9568 | val loss=0.4733 acc=0.8674 f1=0.8446

  Ep 21/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  20/300 | train loss=0.1330 acc=0.9541 | val loss=0.5474 acc=0.8573 f1=0.8327

  Ep 22/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  21/300 | train loss=0.1131 acc=0.9592 | val loss=0.6204 acc=0.8613 f1=0.8456

  Ep 23/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  22/300 | train loss=0.1209 acc=0.9580 | val loss=0.5905 acc=0.8767 f1=0.8687

  Ep  23/300 | train loss=0.1252 acc=0.9562 | val loss=0.4348 acc=0.8784 f1=0.8668

  Ep  24/300 | train loss=0.1158 acc=0.9601 | val loss=0.5481 acc=0.8793 f1=0.8570

  Ep 26/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  25/300 | train loss=0.1154 acc=0.9617 | val loss=0.4812 acc=0.8663 f1=0.8394

  Ep 27/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  26/300 | train loss=0.1011 acc=0.9647 | val loss=0.6067 acc=0.8616 f1=0.8277

  Ep 28/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  27/300 | train loss=0.1026 acc=0.9639 | val loss=0.4959 acc=0.8744 f1=0.8647

  Ep 29/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  28/300 | train loss=0.1036 acc=0.9666 | val loss=0.5441 acc=0.8715 f1=0.8601

  Ep 30/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  29/300 | train loss=0.0979 acc=0.9661 | val loss=0.5776 acc=0.8636 f1=0.8270

  Ep 31/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  30/300 | train loss=0.0971 acc=0.9664 | val loss=0.5080 acc=0.8683 f1=0.8482

  Ep 32/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  31/300 | train loss=0.0988 acc=0.9670 | val loss=0.6140 acc=0.8721 f1=0.8608

  Ep 33/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  32/300 | train loss=0.0995 acc=0.9674 | val loss=0.6265 acc=0.8596 f1=0.8403

  Ep 34/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  33/300 | train loss=0.0967 acc=0.9667 | val loss=0.6678 acc=0.8590 f1=0.8454

  Ep 35/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  34/300 | train loss=0.1002 acc=0.9675 | val loss=0.5636 acc=0.8628 f1=0.8336

  Ep 36/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  35/300 | train loss=0.0964 acc=0.9689 | val loss=0.5817 acc=0.8346 f1=0.8118

  Ep 37/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  36/300 | train loss=0.0890 acc=0.9694 | val loss=0.4842 acc=0.8782 f1=0.8671

  Ep 38/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  37/300 | train loss=0.0835 acc=0.9710 | val loss=0.5478 acc=0.8697 f1=0.8520

  Ep 39/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  38/300 | train loss=0.0882 acc=0.9695 | val loss=0.4753 acc=0.8607 f1=0.8447

  Ep  39/300 | train loss=0.0740 acc=0.9748 | val loss=0.5100 acc=0.8811 f1=0.8725

  Ep 41/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  40/300 | train loss=0.0830 acc=0.9730 | val loss=0.6261 acc=0.8567 f1=0.8205

  Ep 42/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  41/300 | train loss=0.0765 acc=0.9737 | val loss=0.7192 acc=0.8741 f1=0.8634

  Ep 43/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  42/300 | train loss=0.0874 acc=0.9700 | val loss=0.5643 acc=0.8683 f1=0.8523

  Ep 44/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  43/300 | train loss=0.0748 acc=0.9751 | val loss=0.5947 acc=0.8703 f1=0.8337

  Ep 45/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  44/300 | train loss=0.0802 acc=0.9719 | val loss=0.5279 acc=0.8712 f1=0.8583

  Ep 46/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  45/300 | train loss=0.0772 acc=0.9747 | val loss=0.4950 acc=0.8770 f1=0.8664

  Ep  46/300 | train loss=0.0736 acc=0.9749 | val loss=0.6219 acc=0.8834 f1=0.8750

  Ep 48/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  47/300 | train loss=0.0662 acc=0.9769 | val loss=0.5090 acc=0.8750 f1=0.8585

  Ep 49/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  48/300 | train loss=0.0758 acc=0.9757 | val loss=0.5772 acc=0.8663 f1=0.8528

  Ep  49/300 | train loss=0.0716 acc=0.9765 | val loss=0.5908 acc=0.8848 f1=0.8705

  Ep 51/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  50/300 | train loss=0.0700 acc=0.9769 | val loss=0.5899 acc=0.8770 f1=0.8689

  Ep 52/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  51/300 | train loss=0.0655 acc=0.9804 | val loss=0.4857 acc=0.8622 f1=0.8450

  Ep 53/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  52/300 | train loss=0.0714 acc=0.9768 | val loss=0.5446 acc=0.8700 f1=0.8464

  Ep 54/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  53/300 | train loss=0.0751 acc=0.9768 | val loss=0.6225 acc=0.8613 f1=0.8449

  Ep 55/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  54/300 | train loss=0.0627 acc=0.9797 | val loss=0.5661 acc=0.8741 f1=0.8696

  Ep 56/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  55/300 | train loss=0.0613 acc=0.9804 | val loss=0.5744 acc=0.8744 f1=0.8567

  Ep 57/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  56/300 | train loss=0.0568 acc=0.9810 | val loss=0.5799 acc=0.8758 f1=0.8616

  Ep 58/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  57/300 | train loss=0.0634 acc=0.9786 | val loss=0.6400 acc=0.8726 f1=0.8612

  Ep 59/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  58/300 | train loss=0.0617 acc=0.9797 | val loss=0.4966 acc=0.8773 f1=0.8631

  Ep 60/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  59/300 | train loss=0.0643 acc=0.9791 | val loss=0.6617 acc=0.8526 f1=0.8248

  Ep 61/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  60/300 | train loss=0.0553 acc=0.9813 | val loss=0.5760 acc=0.8782 f1=0.8729

  Ep 62/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  61/300 | train loss=0.0561 acc=0.9812 | val loss=0.5356 acc=0.8718 f1=0.8615

  Ep 63/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  62/300 | train loss=0.0637 acc=0.9807 | val loss=0.5217 acc=0.8840 f1=0.8755

  Ep 64/300 train:   0%|          | 0/1960 [00:00<?, ?it/s]

  Ep  63/300 | train loss=0.0550 acc=0.9824 | val loss=0.5349 acc=0.8750 f1=0.8645

  Ep  64/300 | train loss=0.0536 acc=0.9823 | val loss=0.6387 acc=0.8726 f1=0.8636
  Early stopping at epoch 64 (best epoch 49, val_acc=0.8848)

  Test: 100%|██████████| 401/401 [00:39<00:00, 10.03it/s]

  [vit_l16_imagenet]  accuracy=0.8940  f1=0.8819  latency=17.38ms

  [vit_l16_imagenet]  best_epoch=49  val_acc=0.8848  test_acc=0.8940  f1=0.8819

======================================================================
PATH B  —  CLASSIFIER BENCHMARK SUMMARY
======================================================================
                  accuracy  precision  recall     f1  latency_ms  AP_plastic  AP_paper  AP_metal  AP_glass  AP_other
classifier
vit_l16_imagenet    0.8940     0.8733  0.8923 0.8819     17.3840      0.9565    0.9201    0.9315    0.8751    0.9676
======================================================================

CompletedProcess(args=['/workspace/.venv/bin/python', '/workspace/TrashScan/train/paths/train_path_B.py', '--detector_weights', '/workspace/runs/path_A_5cls/yolov11m_o2o/weights/best.pt', '--crops_dir', '/workspace/processed_5cls', '--output', '/workspace/runs/path_B_gt_b4', '--classifiers', 'vit_l16_imagenet', '--epochs', '300', '--batch', '8', '--lr', '5e-05', '--patience', '15', '--device', '0'], returncode=0)

## 5) Resumo do treino (B1, B3, B4)

In [7]:
run_cmd([
    sys.executable, str(TRAIN_PATH_B_SCRIPT),
    '--detector_weights', str(DETECTOR_WEIGHTS),
    '--crops_dir', str(PROCESSED_DIR),
    '--output', str(B1['run_dir']),
    '--summarize',
])

$ /workspace/.venv/bin/python /workspace/TrashScan/train/paths/train_path_B.py --detector_weights /workspace/runs/path_A_5cls/yolov11m_o2o/weights/best.pt --crops_dir /workspace/processed_5cls --output /workspace/runs/path_B_gt_b1 --summarize

======================================================================
PATH B  —  CLASSIFIER BENCHMARK SUMMARY
======================================================================
            accuracy  precision  recall     f1  latency_ms  AP_plastic  AP_paper  AP_metal  AP_glass  AP_other
classifier
resnet50      0.8809     0.8352  0.8738 0.8524      7.0020      0.9574    0.8884    0.8766    0.8629    0.9555
======================================================================

CompletedProcess(args=['/workspace/.venv/bin/python', '/workspace/TrashScan/train/paths/train_path_B.py', '--detector_weights', '/workspace/runs/path_A_5cls/yolov11m_o2o/weights/best.pt', '--crops_dir', '/workspace/processed_5cls', '--output', '/workspace/runs/path_B_gt_b1', '--summarize'], returncode=0)

In [ ]:
run_cmd([
    sys.executable, str(TRAIN_PATH_B_SCRIPT),
    '--detector_weights', str(DETECTOR_WEIGHTS),
    '--crops_dir', str(PROCESSED_DIR),
    '--output', str(B3['run_dir']),
    '--summarize',
])

$ /workspace/.venv/bin/python /workspace/TrashScan/train/paths/train_path_B.py --detector_weights /workspace/runs/path_A_5cls/yolov11m_o2o/weights/best.pt --crops_dir /workspace/processed_5cls --output /workspace/runs/path_B_gt_b3 --summarize

======================================================================
PATH B  —  CLASSIFIER BENCHMARK SUMMARY
======================================================================
                  accuracy  precision  recall     f1  latency_ms  AP_plastic  AP_paper  AP_metal  AP_glass  AP_other
classifier
vit_b16_imagenet    0.8937     0.8792  0.8871 0.8825      5.2200      0.9609    0.9277    0.9279    0.8893    0.9651
======================================================================

CompletedProcess(args=['/workspace/.venv/bin/python', '/workspace/TrashScan/train/paths/train_path_B.py', '--detector_weights', '/workspace/runs/path_A_5cls/yolov11m_o2o/weights/best.pt', '--crops_dir', '/workspace/processed_5cls', '--output', '/workspace/runs/path_B_gt_b3', '--summarize'], returncode=0)

In [9]:
run_cmd([
    sys.executable, str(TRAIN_PATH_B_SCRIPT),
    '--detector_weights', str(DETECTOR_WEIGHTS),
    '--crops_dir', str(PROCESSED_DIR),
    '--output', str(B4['run_dir']),
    '--summarize',
])

$ /workspace/.venv/bin/python /workspace/TrashScan/train/paths/train_path_B.py --detector_weights /workspace/runs/path_A_5cls/yolov11m_o2o/weights/best.pt --crops_dir /workspace/processed_5cls --output /workspace/runs/path_B_gt_b4 --summarize

======================================================================
PATH B  —  CLASSIFIER BENCHMARK SUMMARY
======================================================================
                  accuracy  precision  recall     f1  latency_ms  AP_plastic  AP_paper  AP_metal  AP_glass  AP_other
classifier
vit_l16_imagenet    0.8940     0.8733  0.8923 0.8819     17.3840      0.9565    0.9201    0.9315    0.8751    0.9676
======================================================================

CompletedProcess(args=['/workspace/.venv/bin/python', '/workspace/TrashScan/train/paths/train_path_B.py', '--detector_weights', '/workspace/runs/path_A_5cls/yolov11m_o2o/weights/best.pt', '--crops_dir', '/workspace/processed_5cls', '--output', '/workspace/runs/path_B_gt_b4', '--summarize'], returncode=0)

## 6) Avaliação combinada sem TTA+WBF (B1, B3, B4)

Esta seção avalia detector + classificador no modo standard.

In [9]:
CLASSIFIER_DIR = B1['run_dir']
OUTPUT_DIR_STANDARD = RESULTS_PATH_B_DIR / 'b1_5cls_gt_standard'

cmd = [
    sys.executable, str(EVAL_PATH_B_COMBINED_SCRIPT),
    '--detector_weights', str(DETECTOR_WEIGHTS),
    '--classifier_dir', str(CLASSIFIER_DIR),
    '--classifiers', B1['classifier'],
    '--data_yaml', str(DATASET_YAML_PATH_B),
    '--output', str(OUTPUT_DIR_STANDARD),
    '--device', str(DEVICE),
    '--imgsz', str(EVAL_IMGSZ),
    '--det_conf', str(EVAL_DET_CONF),
    '--det_iou', str(EVAL_DET_IOU),
]

run_cmd(cmd)

$ /workspace/.venv/bin/python /workspace/TrashScan/eval/evaluate_path_B_combined.py --detector_weights /workspace/runs/path_A_5cls/yolov11m_o2o/weights/best.pt --classifier_dir /workspace/runs/path_B_gt_b1 --classifiers resnet50 --data_yaml /workspace/processed_5cls/dataset_path_B.yaml --output /workspace/results_path_B/b1_5cls_gt_standard --device 0 --imgsz 640 --det_conf 0.001 --det_iou 0.6

Device: cuda:0
Test set: /workspace/processed_5cls/test/path_B/images

Loading detector: /workspace/runs/path_A_5cls/yolov11m_o2o/weights/best.pt

────────────────────────────────────────────────────────────
  Evaluating: resnet50
────────────────────────────────────────────────────────────
  Loaded resnet50: 23.5M params from best.pt

  Running combined inference on 1392 test images...
  TTA+WBF: False

  resnet50: 100%|██████████| 1392/1392 [02:52<00:00,  8.07it/s]

  [resnet50]  mAP50=0.6775  mAP50-95=0.4574  fps=8.1
    AP50 plastic : 0.7014  (n_gt=1313)
    AP50 paper   : 0.6723  (n_gt=280)
    AP50 metal   : 0.6084  (n_gt=265)
    AP50 glass   : 0.7054  (n_gt=88)
    AP50 other   : 0.7003  (n_gt=1263)
  Saved: /workspace/results_path_B/b1_5cls_gt_standard/individual/B_resnet50_combined.json

============================================================
PATH B COMBINED — FINAL COMPARISON
============================================================
Classifier                  mAP50  mAP50-95    FPS
──────────────────────────────────────────────────
  resnet50                 0.6775    0.4574    8.1
============================================================

Summary saved: /workspace/results_path_B/b1_5cls_gt_standard/path_B_combined_summary.json

CompletedProcess(args=['/workspace/.venv/bin/python', '/workspace/TrashScan/eval/evaluate_path_B_combined.py', '--detector_weights', '/workspace/runs/path_A_5cls/yolov11m_o2o/weights/best.pt', '--classifier_dir', '/workspace/runs/path_B_gt_b1', '--classifiers', 'resnet50', '--data_yaml', '/workspace/processed_5cls/dataset_path_B.yaml', '--output', '/workspace/results_path_B/b1_5cls_gt_standard', '--device', '0', '--imgsz', '640', '--det_conf', '0.001', '--det_iou', '0.6'], returncode=0)

In [13]:
CLASSIFIER_DIR = B3['run_dir']
OUTPUT_DIR_STANDARD = RESULTS_PATH_B_DIR / 'b3_5cls_gt_standard'

cmd = [
    sys.executable, str(EVAL_PATH_B_COMBINED_SCRIPT),
    '--detector_weights', str(DETECTOR_WEIGHTS),
    '--classifier_dir', str(CLASSIFIER_DIR),
    '--classifiers', B3['classifier'],
    '--data_yaml', str(DATASET_YAML_PATH_B),
    '--output', str(OUTPUT_DIR_STANDARD),
    '--device', str(DEVICE),
    '--imgsz', str(EVAL_IMGSZ),
    '--det_conf', str(EVAL_DET_CONF),
    '--det_iou', str(EVAL_DET_IOU),
]

run_cmd(cmd)

$ /workspace/.venv/bin/python /workspace/TrashScan/eval/evaluate_path_B_combined.py --detector_weights /workspace/runs/path_A_5cls/yolov11m_o2o/weights/best.pt --classifier_dir /workspace/runs/path_B_gt_b3 --classifiers vit_b16_imagenet --data_yaml /workspace/processed_5cls/dataset_path_B.yaml --output /workspace/results_path_B/b3_5cls_gt_standard --device 0 --imgsz 640 --det_conf 0.001 --det_iou 0.6
Device: cuda:0
Test set: /workspace/processed_5cls/test/path_B/images

Loading detector: /workspace/runs/path_A_5cls/yolov11m_o2o/weights/best.pt

────────────────────────────────────────────────────────────
  Evaluating: vit_b16_imagenet
────────────────────────────────────────────────────────────
  Loaded vit_b16_imagenet: 85.8M params from best.pt

  Running combined inference on 1392 test images...
  TTA+WBF: False

  vit_b16_imagenet: 100%|██████████| 1392/1392 [02:56<00:00,  7.90it/s]

  [vit_b16_imagenet]  mAP50=0.7097  mAP50-95=0.4768  fps=7.9
    AP50 plastic : 0.7082  (n_gt=1313)
    AP50 paper   : 0.7268  (n_gt=280)
    AP50 metal   : 0.6595  (n_gt=265)
    AP50 glass   : 0.7465  (n_gt=88)
    AP50 other   : 0.7076  (n_gt=1263)
  Saved: /workspace/results_path_B/b3_5cls_gt_standard/individual/B_vit_b16_imagenet_combined.json

============================================================
PATH B COMBINED — FINAL COMPARISON
============================================================
Classifier                  mAP50  mAP50-95    FPS
──────────────────────────────────────────────────
  vit_b16_imagenet         0.7097    0.4768    7.9
============================================================

Summary saved: /workspace/results_path_B/b3_5cls_gt_standard/path_B_combined_summary.json

CompletedProcess(args=['/workspace/.venv/bin/python', '/workspace/TrashScan/eval/evaluate_path_B_combined.py', '--detector_weights', '/workspace/runs/path_A_5cls/yolov11m_o2o/weights/best.pt', '--classifier_dir', '/workspace/runs/path_B_gt_b3', '--classifiers', 'vit_b16_imagenet', '--data_yaml', '/workspace/processed_5cls/dataset_path_B.yaml', '--output', '/workspace/results_path_B/b3_5cls_gt_standard', '--device', '0', '--imgsz', '640', '--det_conf', '0.001', '--det_iou', '0.6'], returncode=0)

In [5]:
CLASSIFIER_DIR = B4['run_dir']
OUTPUT_DIR_STANDARD = RESULTS_PATH_B_DIR / 'b4_5cls_gt_standard'

cmd = [
    sys.executable, str(EVAL_PATH_B_COMBINED_SCRIPT),
    '--detector_weights', str(DETECTOR_WEIGHTS),
    '--classifier_dir', str(CLASSIFIER_DIR),
    '--classifiers', B4['classifier'],
    '--data_yaml', str(DATASET_YAML_PATH_B),
    '--output', str(OUTPUT_DIR_STANDARD),
    '--device', str(DEVICE),
    '--imgsz', str(EVAL_IMGSZ),
    '--det_conf', str(EVAL_DET_CONF),
    '--det_iou', str(EVAL_DET_IOU),
]

run_cmd(cmd)

$ /workspace/.venv/bin/python /workspace/TrashScan/eval/evaluate_path_B_combined.py --detector_weights /workspace/runs/path_A_5cls/yolov11m_o2o/weights/best.pt --classifier_dir /workspace/runs/path_B_gt_b4 --classifiers vit_l16_imagenet --data_yaml /workspace/processed_5cls/dataset_path_B.yaml --output /workspace/results_path_B/b4_5cls_gt_standard --device 0 --imgsz 640 --det_conf 0.001 --det_iou 0.6

Creating new Ultralytics Settings v0.0.6 file ✅
View Ultralytics Settings with 'yolo settings' or at '/root/.config/Ultralytics/settings.json'
Update Settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/quickstart/#ultralytics-settings.
Device: cuda:0
Test set: /workspace/processed_5cls/test/path_B/images

Loading detector: /workspace/runs/path_A_5cls/yolov11m_o2o/weights/best.pt

────────────────────────────────────────────────────────────
  Evaluating: vit_l16_imagenet
────────────────────────────────────────────────────────────
  Loaded vit_l16_imagenet: 303.3M params from best.pt

  Running combined inference on 1392 test images...
  TTA+WBF: False

  vit_l16_imagenet: 100%|██████████| 1392/1392 [05:19<00:00,  4.36it/s]

  [vit_l16_imagenet]  mAP50=0.7039  mAP50-95=0.4740  fps=4.4
    AP50 plastic : 0.7124  (n_gt=1313)
    AP50 paper   : 0.7246  (n_gt=280)
    AP50 metal   : 0.6418  (n_gt=265)
    AP50 glass   : 0.7350  (n_gt=88)
    AP50 other   : 0.7054  (n_gt=1263)
  Saved: /workspace/results_path_B/b4_5cls_gt_standard/individual/B_vit_l16_imagenet_combined.json

============================================================
PATH B COMBINED — FINAL COMPARISON
============================================================
Classifier                  mAP50  mAP50-95    FPS
──────────────────────────────────────────────────
  vit_l16_imagenet         0.7039    0.4740    4.4
============================================================

Summary saved: /workspace/results_path_B/b4_5cls_gt_standard/path_B_combined_summary.json

CompletedProcess(args=['/workspace/.venv/bin/python', '/workspace/TrashScan/eval/evaluate_path_B_combined.py', '--detector_weights', '/workspace/runs/path_A_5cls/yolov11m_o2o/weights/best.pt', '--classifier_dir', '/workspace/runs/path_B_gt_b4', '--classifiers', 'vit_l16_imagenet', '--data_yaml', '/workspace/processed_5cls/dataset_path_B.yaml', '--output', '/workspace/results_path_B/b4_5cls_gt_standard', '--device', '0', '--imgsz', '640', '--det_conf', '0.001', '--det_iou', '0.6'], returncode=0)

## 7) Avaliação combinada com TTA+WBF (B1, B3, B4)

Esta seção avalia o mesmo classificador treinado em GT crops, mas com o detector usando TTA multi-scale + WBF.

In [10]:
CLASSIFIER_DIR = B1['run_dir']
OUTPUT_DIR_TTA_WBF = RESULTS_PATH_B_DIR / 'b1_5cls_gt_tta_wbf'

cmd = [
    sys.executable, str(EVAL_PATH_B_COMBINED_SCRIPT),
    '--detector_weights', str(DETECTOR_WEIGHTS),
    '--classifier_dir', str(CLASSIFIER_DIR),
    '--classifiers', B1['classifier'],
    '--data_yaml', str(DATASET_YAML_PATH_B),
    '--output', str(OUTPUT_DIR_TTA_WBF),
    '--device', str(DEVICE),
    '--imgsz', str(EVAL_IMGSZ),
    '--det_conf', str(EVAL_DET_CONF),
    '--det_iou', str(EVAL_DET_IOU),
    '--use_tta_wbf',
    '--tta_scales', *TTA_SCALES,
    '--tta_flip',
    '--tta_wbf_iou', TTA_WBF_IOU,
    '--tta_skip_box_thr', TTA_SKIP_BOX_THR,
]

run_cmd(cmd)

$ /workspace/.venv/bin/python /workspace/TrashScan/eval/evaluate_path_B_combined.py --detector_weights /workspace/runs/path_A_5cls/yolov11m_o2o/weights/best.pt --classifier_dir /workspace/runs/path_B_gt_b1 --classifiers resnet50 --data_yaml /workspace/processed_5cls/dataset_path_B.yaml --output /workspace/results_path_B/b1_5cls_gt_tta_wbf --device 0 --imgsz 640 --det_conf 0.001 --det_iou 0.6 --use_tta_wbf --tta_scales 512 640 768 --tta_flip --tta_wbf_iou 0.55 --tta_skip_box_thr 0.001
Device: cuda:0
Test set: /workspace/processed_5cls/test/path_B/images

Loading detector: /workspace/runs/path_A_5cls/yolov11m_o2o/weights/best.pt

────────────────────────────────────────────────────────────
  Evaluating: resnet50
────────────────────────────────────────────────────────────
  Loaded resnet50: 23.5M params from best.pt

  Running combined inference on 1392 test images...
  TTA+WBF: True
  TTA scales: [512, 640, 768]
  TTA flip: True
  TTA WBF IoU: 0.55
  TTA skip box thr: 0.001

  resnet50: 100%|██████████| 1392/1392 [04:18<00:00,  5.38it/s]

  [resnet50]  mAP50=0.6907  mAP50-95=0.4738  fps=5.4
    AP50 plastic : 0.7164  (n_gt=1313)
    AP50 paper   : 0.7085  (n_gt=280)
    AP50 metal   : 0.6357  (n_gt=265)
    AP50 glass   : 0.6833  (n_gt=88)
    AP50 other   : 0.7096  (n_gt=1263)
  Saved: /workspace/results_path_B/b1_5cls_gt_tta_wbf/individual/B_resnet50_combined.json

============================================================
PATH B COMBINED — FINAL COMPARISON
============================================================
Classifier                  mAP50  mAP50-95    FPS
──────────────────────────────────────────────────
  resnet50                 0.6907    0.4738    5.4
============================================================

Summary saved: /workspace/results_path_B/b1_5cls_gt_tta_wbf/path_B_combined_summary.json

CompletedProcess(args=['/workspace/.venv/bin/python', '/workspace/TrashScan/eval/evaluate_path_B_combined.py', '--detector_weights', '/workspace/runs/path_A_5cls/yolov11m_o2o/weights/best.pt', '--classifier_dir', '/workspace/runs/path_B_gt_b1', '--classifiers', 'resnet50', '--data_yaml', '/workspace/processed_5cls/dataset_path_B.yaml', '--output', '/workspace/results_path_B/b1_5cls_gt_tta_wbf', '--device', '0', '--imgsz', '640', '--det_conf', '0.001', '--det_iou', '0.6', '--use_tta_wbf', '--tta_scales', '512', '640', '768', '--tta_flip', '--tta_wbf_iou', '0.55', '--tta_skip_box_thr', '0.001'], returncode=0)

In [14]:
CLASSIFIER_DIR = B3['run_dir']
OUTPUT_DIR_TTA_WBF = RESULTS_PATH_B_DIR / 'b3_5cls_gt_tta_wbf'

cmd = [
    sys.executable, str(EVAL_PATH_B_COMBINED_SCRIPT),
    '--detector_weights', str(DETECTOR_WEIGHTS),
    '--classifier_dir', str(CLASSIFIER_DIR),
    '--classifiers', B3['classifier'],
    '--data_yaml', str(DATASET_YAML_PATH_B),
    '--output', str(OUTPUT_DIR_TTA_WBF),
    '--device', str(DEVICE),
    '--imgsz', str(EVAL_IMGSZ),
    '--det_conf', str(EVAL_DET_CONF),
    '--det_iou', str(EVAL_DET_IOU),
    '--use_tta_wbf',
    '--tta_scales', *TTA_SCALES,
    '--tta_flip',
    '--tta_wbf_iou', TTA_WBF_IOU,
    '--tta_skip_box_thr', TTA_SKIP_BOX_THR,
]

run_cmd(cmd)

$ /workspace/.venv/bin/python /workspace/TrashScan/eval/evaluate_path_B_combined.py --detector_weights /workspace/runs/path_A_5cls/yolov11m_o2o/weights/best.pt --classifier_dir /workspace/runs/path_B_gt_b3 --classifiers vit_b16_imagenet --data_yaml /workspace/processed_5cls/dataset_path_B.yaml --output /workspace/results_path_B/b3_5cls_gt_tta_wbf --device 0 --imgsz 640 --det_conf 0.001 --det_iou 0.6 --use_tta_wbf --tta_scales 512 640 768 --tta_flip --tta_wbf_iou 0.55 --tta_skip_box_thr 0.001
Device: cuda:0
Test set: /workspace/processed_5cls/test/path_B/images

Loading detector: /workspace/runs/path_A_5cls/yolov11m_o2o/weights/best.pt

────────────────────────────────────────────────────────────
  Evaluating: vit_b16_imagenet
────────────────────────────────────────────────────────────
  Loaded vit_b16_imagenet: 85.8M params from best.pt

  Running combined inference on 1392 test images...
  TTA+WBF: True
  TTA scales: [512, 640, 768]
  TTA flip: True
  TTA WBF IoU: 0.55
  TTA skip box thr: 0.001

  vit_b16_imagenet: 100%|██████████| 1392/1392 [04:21<00:00,  5.33it/s]

  [vit_b16_imagenet]  mAP50=0.7121  mAP50-95=0.4867  fps=5.3
    AP50 plastic : 0.7236  (n_gt=1313)
    AP50 paper   : 0.7459  (n_gt=280)
    AP50 metal   : 0.6610  (n_gt=265)
    AP50 glass   : 0.7185  (n_gt=88)
    AP50 other   : 0.7113  (n_gt=1263)
  Saved: /workspace/results_path_B/b3_5cls_gt_tta_wbf/individual/B_vit_b16_imagenet_combined.json

============================================================
PATH B COMBINED — FINAL COMPARISON
============================================================
Classifier                  mAP50  mAP50-95    FPS
──────────────────────────────────────────────────
  vit_b16_imagenet         0.7121    0.4867    5.3
============================================================

Summary saved: /workspace/results_path_B/b3_5cls_gt_tta_wbf/path_B_combined_summary.json

CompletedProcess(args=['/workspace/.venv/bin/python', '/workspace/TrashScan/eval/evaluate_path_B_combined.py', '--detector_weights', '/workspace/runs/path_A_5cls/yolov11m_o2o/weights/best.pt', '--classifier_dir', '/workspace/runs/path_B_gt_b3', '--classifiers', 'vit_b16_imagenet', '--data_yaml', '/workspace/processed_5cls/dataset_path_B.yaml', '--output', '/workspace/results_path_B/b3_5cls_gt_tta_wbf', '--device', '0', '--imgsz', '640', '--det_conf', '0.001', '--det_iou', '0.6', '--use_tta_wbf', '--tta_scales', '512', '640', '768', '--tta_flip', '--tta_wbf_iou', '0.55', '--tta_skip_box_thr', '0.001'], returncode=0)

In [6]:
CLASSIFIER_DIR = B4['run_dir']
OUTPUT_DIR_TTA_WBF = RESULTS_PATH_B_DIR / 'b4_5cls_gt_tta_wbf'

cmd = [
    sys.executable, str(EVAL_PATH_B_COMBINED_SCRIPT),
    '--detector_weights', str(DETECTOR_WEIGHTS),
    '--classifier_dir', str(CLASSIFIER_DIR),
    '--classifiers', B4['classifier'],
    '--data_yaml', str(DATASET_YAML_PATH_B),
    '--output', str(OUTPUT_DIR_TTA_WBF),
    '--device', str(DEVICE),
    '--imgsz', str(EVAL_IMGSZ),
    '--det_conf', str(EVAL_DET_CONF),
    '--det_iou', str(EVAL_DET_IOU),
    '--use_tta_wbf',
    '--tta_scales', *TTA_SCALES,
    '--tta_flip',
    '--tta_wbf_iou', TTA_WBF_IOU,
    '--tta_skip_box_thr', TTA_SKIP_BOX_THR,
]

run_cmd(cmd)

$ /workspace/.venv/bin/python /workspace/TrashScan/eval/evaluate_path_B_combined.py --detector_weights /workspace/runs/path_A_5cls/yolov11m_o2o/weights/best.pt --classifier_dir /workspace/runs/path_B_gt_b4 --classifiers vit_l16_imagenet --data_yaml /workspace/processed_5cls/dataset_path_B.yaml --output /workspace/results_path_B/b4_5cls_gt_tta_wbf --device 0 --imgsz 640 --det_conf 0.001 --det_iou 0.6 --use_tta_wbf --tta_scales 512 640 768 --tta_flip --tta_wbf_iou 0.55 --tta_skip_box_thr 0.001
Device: cuda:0
Test set: /workspace/processed_5cls/test/path_B/images

Loading detector: /workspace/runs/path_A_5cls/yolov11m_o2o/weights/best.pt

────────────────────────────────────────────────────────────
  Evaluating: vit_l16_imagenet
────────────────────────────────────────────────────────────
  Loaded vit_l16_imagenet: 303.3M params from best.pt

  Running combined inference on 1392 test images...
  TTA+WBF: True
  TTA scales: [512, 640, 768]
  TTA flip: True
  TTA WBF IoU: 0.55
  TTA skip box thr: 0.001

  vit_l16_imagenet: 100%|██████████| 1392/1392 [06:21<00:00,  3.65it/s]

  [vit_l16_imagenet]  mAP50=0.7112  mAP50-95=0.4857  fps=3.7
    AP50 plastic : 0.7277  (n_gt=1313)
    AP50 paper   : 0.7496  (n_gt=280)
    AP50 metal   : 0.6606  (n_gt=265)
    AP50 glass   : 0.7063  (n_gt=88)
    AP50 other   : 0.7118  (n_gt=1263)
  Saved: /workspace/results_path_B/b4_5cls_gt_tta_wbf/individual/B_vit_l16_imagenet_combined.json

============================================================
PATH B COMBINED — FINAL COMPARISON
============================================================
Classifier                  mAP50  mAP50-95    FPS
──────────────────────────────────────────────────
  vit_l16_imagenet         0.7112    0.4857    3.6
============================================================

Summary saved: /workspace/results_path_B/b4_5cls_gt_tta_wbf/path_B_combined_summary.json

CompletedProcess(args=['/workspace/.venv/bin/python', '/workspace/TrashScan/eval/evaluate_path_B_combined.py', '--detector_weights', '/workspace/runs/path_A_5cls/yolov11m_o2o/weights/best.pt', '--classifier_dir', '/workspace/runs/path_B_gt_b4', '--classifiers', 'vit_l16_imagenet', '--data_yaml', '/workspace/processed_5cls/dataset_path_B.yaml', '--output', '/workspace/results_path_B/b4_5cls_gt_tta_wbf', '--device', '0', '--imgsz', '640', '--det_conf', '0.001', '--det_iou', '0.6', '--use_tta_wbf', '--tta_scales', '512', '640', '768', '--tta_flip', '--tta_wbf_iou', '0.55', '--tta_skip_box_thr', '0.001'], returncode=0)

## 8) Ranqueamento entre B1, B3 e B4

In [7]:
rows = []

def add_summary_rows(summary_path: Path, model_label: str, eval_mode: str):
    if not summary_path.exists():
        print(f'[warn] Resultado não encontrado para {model_label} ({eval_mode}): {summary_path}')
        return
    data = json.loads(summary_path.read_text())
    if isinstance(data, list):
        for row in data:
            row = dict(row)
            row['model'] = model_label
            row['eval_mode'] = eval_mode
            rows.append(row)
    else:
        row = dict(data)
        row['model'] = model_label
        row['eval_mode'] = eval_mode
        rows.append(row)

for cfg in CONFIGS:
    add_summary_rows(
        RESULTS_PATH_B_DIR / (cfg['key'] + '_5cls_gt_standard') / 'path_B_combined_summary.json',
        cfg['label'],
        'standard',
    )
    add_summary_rows(
        RESULTS_PATH_B_DIR / (cfg['key'] + '_5cls_gt_tta_wbf') / 'path_B_combined_summary.json',
        cfg['label'],
        'tta_wbf',
    )

if not rows:
    print('Nenhum resumo encontrado ainda.')
else:
    df = pd.DataFrame(rows)
    score_col = 'mAP50'
    cols = [c for c in ['model', 'eval_mode', 'classifier', score_col, 'mAP50', 'mAP50_95', 'fps', 'inference_mode'] if c in df.columns]

    if score_col not in df.columns:
        print('[warn] Coluna mAP50 não encontrada; não é possível ranquear.')
    else:
        for mode in ['standard', 'tta_wbf']:
            df_mode = df[df['eval_mode'] == mode].copy()
            if df_mode.empty:
                print(f'[warn] Sem dados para modo: {mode}')
                continue
            df_mode = df_mode.sort_values(by=[score_col], ascending=False).reset_index(drop=True)
            print(f'Ranking ({mode}) - ordenado por {score_col}')
            display(df_mode[cols])

Ranking (standard) - ordenado por mAP50

,model,eval_mode,classifier,mAP50,mAP50,mAP50_95,fps,inference_mode
0,B3 (vit_b16_imagenet),standard,vit_b16_imagenet,0.70972,0.70972,0.47684,7.90,standard
1,B4 (vit_l16_imagenet),standard,vit_l16_imagenet,0.70386,0.70386,0.47398,4.36,standard
2,B1 (resnet50),standard,resnet50,0.67755,0.67755,0.45743,8.07,standard

Ranking (tta_wbf) - ordenado por mAP50

,model,eval_mode,classifier,mAP50,mAP50,mAP50_95,fps,inference_mode
0,B3 (vit_b16_imagenet),tta_wbf,vit_b16_imagenet,0.71208,0.71208,0.48674,5.33,tta_wbf
1,B4 (vit_l16_imagenet),tta_wbf,vit_l16_imagenet,0.71121,0.71121,0.48569,3.65,tta_wbf
2,B1 (resnet50),tta_wbf,resnet50,0.69069,0.69069,0.47384,5.38,tta_wbf